language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
os:
  - linux
  - osx
script:
  - yarn test
after_success:
  - yarn docs
  - mv docs/position.ts/* out
deploy:
  provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
