language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
os:
  - linux
  - osx
script:
  - npm test
after_success:
  - npm run docs
  - mv docs/meethere/* out
deploy:
  provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: meethere.js.org
  on:
    branch: master
